version: '2'

services:
    db:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: root
            MYSQL_PASSWORD: root
    php:
        build: docker/php7-fpm
        volumes:
            - .:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/app/logs
    nginx:
        build: docker/nginx
        ports:
            - 80:80
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx